### ISSUE TITLE
Require 'sends' literal only once

### ISSUE THREAD

**Issue by matthewadams** [SciSpike/yaktor-dsl-xtext#16]
Instead of
```
agent Thing concerning Foo {
  sends go
  sends stop
  sends flip
  sends reverse
}
```
allow
```
agent Thing concerning Foo {
  sends go stop flip reverse
}
```

**Comment by pgraff** [comment]
Make sure this does not break the generator of documentation...

Message typed on an iPhone. 
Spelling errors are likely...

**Comment by matthewadams** [comment]
@pgraff, all changes will preserve existing functionality, except where we're intentionally breaking backward compatibility, usually where the prior capability didn't make sense.  This issue, along with #15, #17 & #18 were discussed *ad nauseum* with @jkamke.
