### ISSUE TITLE
Ensure complete verbose/terse equivalents in conversation DSL

### ISSUE THREAD

**Issue by matthewadams** [SciSpike/yaktor-dsl-xtext#19]
The conversation DSL supports both a verbose, or friendly, set of literals as well as a terse, or more programmatic, set of literals.

This issue is to ensure that we go through the conversation DSL exhaustively, examining each verbose literal to determine whether it should have a terse analog, and, if so, decide what the terse analog literal should be.

**Comment by jkamke** [comment]
closed by #22
