### ISSUE TITLE
FIND endpoints param missing (s)

### ISSUE THREAD

**Issue by peterjunsworth** [SciSpike/yaktor-dsl-xtext#25]
The generated FIND endpoint checks to see if there is a pageSize query parameter however currently it checks against req.param when it should be req.params

**Comment by matthewadams** [comment]
According to the expressjs 4.x docs,
* [`req.params`](http://expressjs.com/en/4x/api.html#req.params) is a property for path variables/named route parameters only,
* [`req.query`](http://expressjs.com/en/4x/api.html#req.query) is a property to get query parameters only, and
* [`req.body`](http://expressjs.com/en/4x/api.html#req.body) is a property for key-value pairs of data submitted in the request body only (basically, form data).

[`req.param(name)`](http://expressjs.com/en/4x/api.html#req.param) is a deprecated method that searches for the value of `name` from `req.params[name]`, then `req.body[name]`, then `req.query[name]`, in that order, so can be used when you don't care whether the value is coming from.  The only time it would matter where you got ``name``'s value from is when there are path variables, form data and/or query parameters with the same name.

If `pageSize` is indeed a query parameter, then it should be looking only at `req.query.pageSize`.  If `pageSize` is form data, then it should be looking at `req.params.pageSize`.

@peterjunsworth, you're asserting that we should only be looking `req.params`, so form data.  I'm not sure we want to be that restrictive.  As long as there's no route with a path variable called `pageSize`, `req.param('pageSize')` would return the correct value regardless of its source.

**Comment by matthewadams** [comment]
@peterjunsworth nevermind.  @jkamke filled me in.  I'll fix and release a patch.
