### ISSUE TITLE
Incorrect code generation of resource/find

### ISSUE THREAD

**Issue by pgraff** [SciSpike/yaktor-dsl-xtext#4]
When generating code in the 'def' file for find, the generator inserts a constant for a variable.

E.g., say:
resource /foo over SomeType offers (... find) ...

Part of the find method is generated as:
converter.to('SomeType', domains, function(err, dtos, 0) {

The '0' is bad... It should probably have been:
converter.to('drivethrough.Chain', domains, function(err, dtos, total) {

**Comment by jkamke** [comment]
I think this has already been fixed. Please check with the latest 0.3.0-pre
