### ISSUE TITLE
Modify custom function signature generation for state transitions to change argument name "data" to name of event

### ISSUE THREAD

**Issue by gacord23** [SciSpike/yaktor-dsl-xtext#7]
This is purely a usability issue.

Given state transition
`receives custom checkIn becomes waitingForAssistance sends checkedIn`
the generator creates custom function signature
`function(causedByEventName,meta,data,done)`

Since the term `data` wasn't meaningful to me, I inadvertently overwrote it in my custom routine.  Had the generator used the event name `checkIn` instead of `data`, like
`function(causedByEventName,meta,checkIn,done)`
it may have made things more obvious.

**Comment by matthewadams** [comment]
FYI, started work in branch https://github.com/SciSpike/yaktor-dsl-xtext/tree/7.

**Comment by matthewadams** [comment]
This issue was moved to SciSpike/yaktor-issues#5
