### ISSUE TITLE
naming indexes/constraints

### ISSUE THREAD

**Issue by jkamke** [SciSpike/yaktor-dsl-xtext#8]
Support naming indexes in order to facilitate automatic updates when indexes gain/lose fields. Without defining a name mongo automatically generates a unique name, and your database ends up with multiple indexes where only one is desired.

Depends on mongoose/mongo having the ability to properly update the definition of existing indexes.

**Comment by matthewadams** [comment]
This issue was moved to SciSpike/yaktor-issues#4
